"""make first_name and last_name nullable

Revision ID: cf2b49cc1f4f
Revises: df11c99c79bf
Create Date: 2025-06-29 15:11:14.132940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf2b49cc1f4f'
down_revision: Union[str, None] = 'df11c99c79bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_sessions', 'conversation_context',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('conversation_sessions', 'full_conversation',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('feedback', 'content',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('feedback', 'original_text',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('feedback', 'corrected_text',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('feedback', 'explanation',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('feedback', 'recommended_practice',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('messages', 'content',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('messages', 'detected_errors',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('messages', 'corrections',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'preferred_topics',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('users', 'learning_goals',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'learning_goals',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'preferred_topics',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('messages', 'corrections',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('messages', 'detected_errors',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('messages', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.alter_column('feedback', 'recommended_practice',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('feedback', 'explanation',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('feedback', 'corrected_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('feedback', 'original_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('feedback', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.alter_column('conversation_sessions', 'full_conversation',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('conversation_sessions', 'conversation_context',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
